name: Generate lockfile

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  DSH_REGISTRY: https://registry.npmjs.org

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
        with:
          version: 11.21.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 22.19.0
      - run: pnpm install --lockfile-only --registry=${{ env.DSH_REGISTRY }}
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: pnpm-lock
          path: pnpm-lock.yaml
          if-no-files-found: error
